---
version: '3'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - 8000:8000
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: 192.168.0.10/sgpc
      DB_LIB_PATH: /opt/oracle/instantclient_21_4
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload